---
title: "Carte interactive des stations AWS"
author: "Ousmane"
format: 
  html:
    page-layout: full
execute:
  echo: true
  warning: false
  message: false
---

```{r setup, include=FALSE}

library(tmap)
library(tidyverse)
library(sf)
tmap_mode("view")
```

```{r}
# Charger les données stations (encodage latin1)
data <- read_csv2("network/all_station.csv", locale = locale(encoding = "latin1"))

# Charger les shapefiles
bvn <- read_sf("shape_ec_aen/EC_AEN.shp") %>%
  st_transform(crs = 4326)

reclim <- read_sf("reclim/zone_reclim.shp") %>%
  st_transform(crs = 4326)

# Nettoyer et filtrer les données, transformer en objet sf
data_sf <- data %>%
  drop_na(lon, lat) %>%
  filter(station != "Bazega", station != "Vallée-Du-Kou", type !="manual") %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) %>%
  st_filter(bvn)

```

```{r}


tm_shape(bvn) +
  tm_polygons(alpha = 0.3, border.col = "blue", fill = "yellow") +

tm_shape(reclim) +
  tm_polygons(alpha = 0.1, border.col = "red") +

tm_shape(data_sf) +
  tm_dots(size = 0.5)
```

```{r}
library(leaflet)
#layout:full
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(data = bvn, fillOpacity = 0.2, color = "blue") %>%
  addPolygons(data = reclim, fillOpacity = 0.1, color = "red") %>%
  addCircleMarkers(data = data_sf, radius = 4, label = ~station) %>%
  htmlwidgets::onRender("
    function(el, x) {
      this.on('click', function(e) {
        alert('Longitude: ' + e.latlng.lng + '\\nLatitude: ' + e.latlng.lat);
      });
    }
  ")

```
